DatalogiForAlle/AgentsPy

README.md
Så folk kan se hvem vi er, hvem de skal kontakte
=> Tilføj forfatter

examples/stupid/stupid01-basic.py, examples/stupid/stupid02-buggrowth.py, examples/stupid/stupid03-habitatcells.py, examples/stupid/stupid05-modelparameters.py, examples/stupid/stupid06-histograms.py, examples/stupid/stupid07-stopcondition.py, examples/stupid/stupid08-write-data-to-file.py, examples/stupid/stupid09-agent-order-randomized.py, examples/stupid/stupid10-agent-order-sorted.py, examples/stupid/stupid11-ranked-neighbour-tiles.py, examples/stupid/stupid12-mortality-reproduction.py, examples/stupid/stupid13-population-graph.py, examples/stupid/stupid14-normal-distribution.py, examples/stupid/stupid15-reading-habitat-data.py, examples/stupid/stupid16-multiple-agent-types.py
- Added names to files and UI of all stupidmodels (no longer named "Dum dum")
- Reduce tile_size, so all use the same tile_size
- Fix a few bugs (e.g. add a flush after writing to files)
=> Reorganize and add names to stupidmodel, reduze tile_size, and fix a few bugs

agents/ui.py, examples/epidemic.py
Instead of each button and graph having their own timer, their updates are now managed through a main-loop.
=> Main timer loop

agents/model.py, agents/ui.py, docs/source/model.rst, examples/epidemic.py
`on_close` now allows defining a function that can be run when the simulation window is closed.
=> Running code on exit

agents/model.py, agents/ui.py, examples/electric.py
Agents can now be given different icons using the field `Agent.icon` and the enum `AgentIcon`.
=> Agent icons

agents/ui.py
Certain combinations of UI-setup (adding/not adding buttons etc.) were causing segfaults and making the program stuck.
As far as I can tell, it was caused by this line in `ui.py`:
`Application(model)`
Since the application was not assigned to a variable, part of it would be garbage-collected, which would cause the segfaults.
It has been fixed (hacked?) with the following change:
`app = Application(model)`
=> Fixed some mysterious ui-issues

agents/model.py
This should eliminate flickering, since the agents will maintain the same order (although I am not sure, as I could not not replicate the flickering).
=> Model.agents from set to list

agents/model.py, examples/stupid/stupid01-basic.py, examples/stupid/stupid02-buggrowth.py, examples/stupid/stupid03-habitatcells.py, examples/stupid/stupid05-modelparameters.py, examples/stupid/stupid06-histograms.py, examples/stupid/stupid07-stopcondition.py, examples/stupid/stupid08-write-data-to-file.py, examples/stupid/stupid09-agent-order-randomized.py, examples/stupid/stupid10-agent-order-sorted.py, examples/stupid/stupid11-ranked-neighbour-tiles.py, examples/stupid/stupid12-mortality-reproduction.py, examples/stupid/stupid13-population-graph.py, examples/stupid/stupid14-normal-distribution.py, examples/stupid/stupid15-reading-habitat-data.py, examples/stupid/stupid16-multiple-agent-types.py
I'm working on simplifying the stupid model code, still on my TODO is to simplify stupid12 to stupid16.
Some notes for further simplication of the code i've been through so far:
- perhaps we shouldn't even have and use agents_random() in stupid09 and just use random.shuffle(), when model.agents is converted to a list?
- perhaps stupid08, we shouldn't use a global variable to hold the file handle, but use a model variable?
- would be nice if we could avoid update_current_tile()
- would be nice if `Agent.align()` was named `Agent.center_in_tile()` or similar
- perhaps all agents should have a reference to their model, instead of the requirement to pass model into all setup/step functions and into all "action" functions
=> Simplification of stupid model code

.gitignore, agents/model.py, agents/ui.py
=> Fixes from PR #67 moved to a new branch, to avoid the git catastrophe that happened over there

.gitignore, agents/model.py, agents/ui.py
* `contains_agent_type(agents, agent_type)`: Returns a boolean indicating whether an agent of `agent_type` is in `agents`.
* `remove_agents_type(agents, agent_type)`: Returns `agents` where all agents of type `agent_type` are removed.
* `only_agents_type(agents, agent_type)`: Returns `agents` where all agents _not_ of type `agent_type` are removed.
* `agents_ordered(agents, variable, increasing=True)`: Returns the `agents` list, sorted by `variable` in either increasing or decreasing order. Prints an error if not all agents in the list have the attribute.
* `destroy_agents(agents)`: Destroys all agents in `agents`.
=> Utility functions for working on lists of agents

agents/model.py, agents/ui.py, examples/epidemic.py
Changes to the graph API in order to support using actual attributes instead of K/V-pairs in the model object .
=> Improved the graph API

agents/model.py, examples/bnb_pandemic.py, examples/stupid/stupid14-normal-distribution.py
Updating the examples so all of them can actually run.
=> Updating examples (WIP)

agents/model.py, tests/test_model.py
Just a few small changes, to make the test suite succeed. Really weird floating point error happened, so I've made a hack to get it to work. Hopefully it will fix it in all cases, but if something with wrapping starts to fail, we might need to look at it again.
=> Fix a few problems that made the test suite fail

agents/ui.py
=> Graph legends

agents/model.py, examples/epidemic.py
Before:
```
model.add_toggle_button("Go", step)
```
Now:
```
model.add_button("Go", step, toggle=True)
```
=> Joining add_button and add_toggle_button

examples/epidemic.py
A percentage of agents can be specified to stand still using the slider.
=> Alternative social distancing

agents/ui.py, docs/source/epidemi/epidemi_del1.rst, docs/source/epidemi/epidemi_del2.rst
Fixes #118, as well as a few small documentation issues
=> Avoid histogram flickering between various y-max values

agents/model.py, agents/ui.py, examples/epidemic.py
Known issue: all lines drawn by an agent will constantly change color to match the agent (even lines that are not currently "being drawn" by the agent).
=> pen_down and pen_up

examples/epidemic_vaccine.py
Note that this uses the model style from the tutorial rather than the one from the `examples` directory
=> Epidemic model w. vaccine rate

agents/model.py, agents/ui.py, tutorials/models/epidemic-4.3.py
Simulation elements (tiles, agents, shapes and paths) are now drawn on different layers, allowing for some optimization when drawing tiles and paths in particular.
=> Layered rendering
